branch-defaults:
  simple-v2:
    environment: cloudstore-simple
global:
  application_name: cloudstore
  default_ec2_keyname: cloudstore-web
  default_platform: 64bit Amazon Linux 2017.09 v2.7.7 running Tomcat 8 Java 8
  default_region: us-west-2
  profile: mfadmin
  sc: git
deploy:
  artifact: target/cloudstore-boot-0.0.2-simple-SNAPSHOT.war
