spring:
  jpa:
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.generate_statistics: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    platform: h2
    initialize: false
    url: jdbc:h2:~/tpcw;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  h2:
    console:
      path: /h2-console
      enabled: true
