spring:
  jpa:
    show-sql: false
    properties:
      hibernate.hbm2ddl.auto: none
      hibernate.generate_statistics: false
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    platform: mysql
    initialize: false
#    url: jdbc:h2:~/tpcw;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://localhost:3306/tpcw
    username: root
    password:
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
