spring:
  jpa:
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: validate
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    platform: mysql
    initialize: false
    url: jdbc:mysql://aa15qy9kq3c7pt6.c7vtta3fbhu3.us-west-2.rds.amazonaws.com:3306/tpcw
    username: root
    password: rootroot

cloudstore:
  jms:
    broker-url: tcp://ec2-34-217-209-119.us-west-2.compute.amazonaws.com:61616
    payment: payment-queue
    payment-status: payment-status-queue